- name: "Add custom .xinitrc at '{{ user_xinitrc_path }}'"
  ansible.builtin.template:
    dest: "{{ user_xinitrc_path }}"
    src: 'xinitrc.j2'
    owner: "{{ user_name }}"
    mode: '755'
    force: true
  become: true
  become_user: root
  when: create_user_xinitrc_and_xsession

- name: "Remove any existing custom .xinitrc at '{{ user_xinitrc_path }}'"
  ansible.builtin.file:
    path: "{{ user_xinitrc_path }}"
    state: absent
  become: true
  become_user: root
  when: not create_user_xinitrc_and_xsession

- name: "Create '{{ user_xinitrc_path }}' as symlink to '{{ user_xsession_path }}'"
  ansible.builtin.file:
    src: "{{ user_xinitrc_path }}"
    dest: "{{ user_xsession_path }}"
    owner: "{{ user_name }}"
    mode: '755'
    state: link
    force: true
  become: true
  become_user: root
  when: create_user_xinitrc_and_xsession

- name: "Remove any existing custom .xsession at '{{ user_xsession_path }}'"
  ansible.builtin.file:
    path: "{{ user_xsession_path }}"
    state: absent
  become: true
  become_user: root
  when: not create_user_xinitrc_and_xsession

