- name: "Add custom .xinitrc at '{{ xorg_user_xinitrc_path }}'"
  ansible.builtin.template:
    dest: "{{ xorg_user_xinitrc_path }}"
    src: 'xinitrc.j2'
    owner: "{{ xorg_user_name }}"
    mode: '755'
    force: true
  become: true
  become_user: root
  when: xorg_create_user_xinitrc_and_xsession

- name: "Remove any existing custom .xinitrc at '{{ xorg_user_xinitrc_path }}'"
  ansible.builtin.file:
    path: "{{ xorg_user_xinitrc_path }}"
    state: absent
  become: true
  become_user: root
  when: not xorg_create_user_xinitrc_and_xsession

