- name: "Run all role tasks for Linux"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    system_xserver_path: "{{ linux_system_xserver_path }}"
    system_xresources_path: "{{ linux_system_xresources_path }}"
    system_xmodmap_path: "{{ linux_system_xmodmap_path }}"
    system_xinitrc_d_dir: "{{ linux_system_xinitrc_d_dir }}"
    system_xprofile_path: "{{ linux_system_xprofile_path }}"
  when: ansible_system == "Linux"

- name: "Run all role tasks for FreeBSD"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    system_xserver_path: "{{ freebsd_system_xserver_path }}"
    system_xresources_path: "{{ freebsd_system_xresources_path }}"
    system_xmodmap_path: "{{ freebsd_system_xmodmap_path }}"
    system_xinitrc_d_dir: "{{ freebsd_system_xinitrc_d_dir }}"
    system_xprofile_path: "{{ freebsd_system_xprofile_path }}"
  when: ansible_os_family == "FreeBSD"

