- name: "Run all role tasks for Ubuntu"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    xorg_package_names: "{{ xorg_ubuntu_package_names }}"
    system_xresources_path: "{{ xorg_linux_system_xresources_path }}"
    system_xmodmap_path: "{{ xorg_linux_system_xmodmap_path }}"
    system_xinitrc_d_dir: "{{ xorg_linux_system_xinitrc_d_dir }}"
    system_xprofile_path: "{{ xorg_linux_system_xprofile_path }}"
    system_xorg_conf_dir: "{{ xorg_linux_system_xorg_conf_dir }}"
  when: ansible_distribution == "Ubuntu"

- name: "Run all role tasks for Arch Linux"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    xorg_package_names: "{{ xorg_archlinux_package_names }}"
    system_xresources_path: "{{ xorg_linux_system_xresources_path }}"
    system_xmodmap_path: "{{ xorg_linux_system_xmodmap_path }}"
    system_xinitrc_d_dir: "{{ xorg_linux_system_xinitrc_d_dir }}"
    system_xprofile_path: "{{ xorg_linux_system_xprofile_path }}"
    system_xorg_conf_dir: "{{ xorg_linux_system_xorg_conf_dir }}"
  when: ansible_os_family == "Archlinux"

- name: "Run all role tasks for FreeBSD"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    xorg_package_names: "{{ xorg_freebsd_package_names }}"
    system_xresources_path: "{{ xorg_freebsd_system_xresources_path }}"
    system_xmodmap_path: "{{ xorg_freebsd_system_xmodmap_path }}"
    system_xinitrc_d_dir: "{{ xorg_freebsd_system_xinitrc_d_dir }}"
    system_xprofile_path: "{{ xorg_freebsd_system_xprofile_path }}"
    system_xorg_conf_dir: "{{ xorg_freebsd_system_xorg_conf_dir }}"
  when: ansible_os_family == "FreeBSD"

