- name: "Export vars for other roles"
  ansible.builtin.include_tasks: export_vars/main.yml

- name: "Install all Xorg packages"
  ansible.builtin.include_tasks: install/main.yml

- name: "Configure custom .xinitrc for user '{{ xorg_user_name }}'"
  ansible.builtin.include_tasks: config_user_xinitrc/main.yml

- name: "Configure custom .Xresources for user '{{ xorg_user_name }}'"
  ansible.builtin.include_tasks: config_user_xresources/main.yml

- name: "Configure xorg.conf.d external graphics card number/bus"
  ansible.builtin.include_tasks: config_video_card/main.yml

- name: "Configure xorg.conf.d monitors layout and resolutions"
  ansible.builtin.include_tasks: config_monitors/main.yml

- name: "Configure xorg.conf.d key-repeat settings"
  ansible.builtin.include_tasks: config_key_repeat/main.yml

