- name: "Install base Xorg packages"
  ansible.builtin.include_tasks: install_xorg/main.yml

- name: "Export vars for other roles"
  ansible.builtin.include_tasks: export_vars/main.yml

- name: "Install xrdb packages required for custom user .xinitrc"
  ansible.builtin.include_tasks: install_xrdb/main.yml

- name: "Install xmodmap packages required for custom user .xinitrc"
  ansible.builtin.include_tasks: install_xmodmap/main.yml

- name: "Configure custom .xinitrc for user '{{ xorg_user_name }}'"
  ansible.builtin.include_tasks: config_user_xinitrc/main.yml

- name: "Configure custom .Xresources for user '{{ xorg_user_name }}'"
  ansible.builtin.include_tasks: config_user_xresources/main.yml

- name: "Configure xorg.conf.d key-repeat settings"
  ansible.builtin.include_tasks: config_key_repeat/main.yml

