- name: "Install base Xorg packages"
  ansible.builtin.include_tasks: install_xorg/main.yml

- name: "Install xrdb packages required for custom user .xinitrc"
  ansible.builtin.include_tasks: install_xrdb/main.yml

- name: "Install xmodmap packages required for custom user .xinitrc"
  ansible.builtin.include_tasks: install_xmodmap/main.yml

- name: "Configure custom .xinitrc for user '{{ user_name }}'"
  ansible.builtin.include_tasks: user_xinitrc/main.yml

- name: "Configure xorg.conf.d key repeat-delay/repeat-rate"
  ansible.builtin.include_tasks: key_repeat/main.yml

# - name: "Configure custom .xserverrc for user '{{ user_name }}'"
#   ansible.builtin.include_tasks: user_xserverrc/main.yml

