- name: "Set system key-repeat settings in '{{ system_xorg_key_repeat_conf_path }}'"
  ansible.builtin.template:
    dest: "{{ system_xorg_key_repeat_conf_path }}"
    src: 'key_repeat.j2'
    owner: 'root'
    mode: '644'
    force: true
  become: true
  become_user: root

