- name: "Add custom .xsession at '{{ xorg_user_xsession_path }}'"
  ansible.builtin.template:
    dest: "{{ xorg_user_xsession_path }}"
    src: 'xsession.j2'
    owner: "{{ xorg_user_name }}"
    mode: '755'
    force: true
  become: true
  become_user: root

